"""プロジェクトへの変更を表すコマンドと、その履歴

UI からの操作も AI エージェントからの操作も、必ずここを通る 同じ入口にすることで
Undo の対象から漏れる変更が存在しなくなり、AI の一連の操作をまとめて取り消す
チェックポイントも自然に成立する
"""

from sashimono.core.commands.base import Command
from sashimono.core.commands.edit import (
    AddClip,
    AddMedia,
    AddTrack,
    MoveClip,
    MoveClips,
    RemoveClip,
    RemoveClips,
    RemoveMedia,
    RemoveTrack,
    RenameProject,
    RippleCut,
    SetBlending,
    SetResolution,
    SetTrackHeights,
    SetTrackState,
    SetTranscript,
    SplitClip,
    TrimClip,
    TrimClips,
)
from sashimono.core.commands.effects import (
    AddEffect,
    ClearKeyframes,
    MoveEffect,
    MoveKeyframe,
    ParamPath,
    ParamTarget,
    RemoveEffect,
    RemoveKeyframe,
    SetClipProperty,
    SetEffectEnabled,
    SetKeyframe,
    SetParam,
    SetSource,
    resolve_param,
)
from sashimono.core.commands.group import GroupClips, UngroupClips
from sashimono.core.commands.history import Document, HistoryEntry
from sashimono.core.commands.insert import (
    DEFAULT_GENERATED_FRAMES,
    DEFAULT_STILL_FRAMES,
    insert_generated,
    insert_media,
)
from sashimono.core.commands.scene import (
    DEFAULT_SCENE_FRAMES,
    AddScene,
    InScene,
    RemoveScene,
    RenameScene,
    insert_scene,
    new_scene,
)
from sashimono.core.commands.subtitle import (
    AddSegment,
    MergeWithNext,
    RemoveSegment,
    RetimeSegment,
    SetSegmentText,
    SplitSegment,
    burn_subtitles,
)
from sashimono.core.commands.work_area import SetWorkArea, export_range

__all__ = [
    "DEFAULT_GENERATED_FRAMES",
    "DEFAULT_SCENE_FRAMES",
    "DEFAULT_STILL_FRAMES",
    "AddClip",
    "AddEffect",
    "AddMedia",
    "AddScene",
    "AddSegment",
    "AddTrack",
    "ClearKeyframes",
    "Command",
    "Document",
    "GroupClips",
    "HistoryEntry",
    "InScene",
    "MergeWithNext",
    "MoveClip",
    "MoveClips",
    "MoveEffect",
    "MoveKeyframe",
    "ParamPath",
    "ParamTarget",
    "RemoveClip",
    "RemoveClips",
    "RemoveEffect",
    "RemoveKeyframe",
    "RemoveMedia",
    "RemoveScene",
    "RemoveSegment",
    "RemoveTrack",
    "RenameProject",
    "RenameScene",
    "RetimeSegment",
    "RippleCut",
    "SetBlending",
    "SetClipProperty",
    "SetEffectEnabled",
    "SetKeyframe",
    "SetParam",
    "SetResolution",
    "SetSegmentText",
    "SetSource",
    "SetTrackHeights",
    "SetTrackState",
    "SetTranscript",
    "SetWorkArea",
    "SplitClip",
    "SplitSegment",
    "TrimClip",
    "TrimClips",
    "UngroupClips",
    "burn_subtitles",
    "export_range",
    "insert_generated",
    "insert_media",
    "insert_scene",
    "new_scene",
    "resolve_param",
]
